#!/usr/bin/with-contenv bash
umask 022

WRITERS="authenticated"
READERS="authenticated"

[[ "${ANON_READ}" = "true" ]] && \
	READERS="anon"

[[ "${ANON_WRITE}" = "true" ]] && \
	WRITERS="anon"

[[ -n "${USERNAME}" && -n "${PASSWORD}" ]] && \
	PARAMS+=("username=${USERNAME}" "password=${PASSWORD}")

[[ -n "${AUTH_HEADER}" ]] && \
	PARAMS+=("authenticated-user-header=${AUTH_HEADER}")

[[ -n "${CREDENTIALS_CSV}" ]] && \
	PARAMS+=("credentials=${CREDENTIALS_CSV}")

PARAMS+=("readers=(${READERS})")
PARAMS+=("writers=(${WRITERS})")

exec \
	s6-setuidgid abc tiddlywiki /data --listen host=0.0.0.0 "${PARAMS[@]}"
