#!/usr/bin/with-contenv bash

# Display variables for troubleshooting
echo -e "Variables set:\\n\
PGID=${PGID}\\n\
PUID=${PUID}\\n\
TZ=${TZ}\\n\
REMOTE_PATH=${REMOTE_PATH}\\n\
PARAMS=${PARAMS}\\n\
FIX_MOUNT=${FIX_MOUNT}\\n\
CONFIG=${CONFIG}\\n\
"

# check to make sure that the required variables are set
[[ -z "$REMOTE_PATH" ]] && \
  echo "Please pass your source as an environment variable in your docker run command. See docker info for more details." && \
  sleep infinity

# permissions
chown -R abc:abc \
	/config
