#!/usr/bin/with-contenv bash

# Display variables for troubleshooting
echo -e "Variables set:\\n\
PGID=${PGID}\\n\
PUID=${PUID}\\n\
TZ=${TZ}\\n\
CONFIG=${CONFIG}\\n\
"

# permissions
chown -R abc:abc \
	/config
